"""
train.py: 
- Reads data/cleaned/.
- Trains RandomForestRegressor model on data
- Saves artifacts/model.joblib.

Citation: 
"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
import joblib
import yaml
from sklearn.ensemble import RandomForestRegressor
import pandas as pd

with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

# Using yaml to define paths
xtrain_path = config["paths"]["X_train"]
xtest_path = config["paths"]["X_test"]
ytrain_path = config["paths"]["y_train"]
ytest_path = config["paths"]["y_test"]

# Load X_train, X_test, y_train, y_test from data/cleaned
X_train = pd.read_csv(xtrain_path)
X_test = pd.read_csv(xtest_path)

y_train = pd.read_csv(ytrain_path).squeeze()
y_test = pd.read_csv(ytest_path).squeeze()
# The above code snippet was generated by ChatGPT 5.1 at 8:22p on 11/22/25.

# Model selection
model = RandomForestRegressor(n_estimators=100)

# Fitting model to X_train, y_train
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Printing model acccuracy: Returns 94.7%
# print(model.score(X_test, y_test))

# Begin cited block: OpenAI. (2025, November 22). ChatGPT response to a request for regression model evaluation metrics [Large language model]. https://chat.openai.com/
# This cited block studies model accuracy
# mse = mean_squared_error(y_test, y_pred)
# rmse = np.sqrt(mse)
# mae = mean_absolute_error(y_test, y_pred)
# r2 = r2_score(y_test, y_pred)
# mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

"""
Perfornance:
(base) averyestopinal@Averys-MacBook-Pro-3 Module3Project % python train.py
R² Score: 0.9474
RMSE: 0.5282
MAE: 0.3005
MAPE: 0.37%
"""

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"MAPE: {mape:.2f}%")

#------------------------------------END CITED BLOCK-----------------------


# Saving model to artifacts
joblib.dump(model, "artifacts/model.joblib")
# The above code snippet was generated by chatGPT 5.1 at 6:16p on 11/22/25.