import os
import yaml
import gradio as gr
import pandas as pd
import requests

API_URL = "http://127.0.0.1:8000/predict_named"

# point to config.yaml so server uses same paths as scripts
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "config.yaml")
if os.path.exists(CONFIG_PATH):
    with open(CONFIG_PATH, "r") as f:
        cfg = yaml.safe_load(f)
else:
    cfg = {}

# read artifacts paths from config 
PREPROCESSOR_PATH = cfg.get("artifacts", {}).get("preprocessor", "artifacts/preprocessor.joblib")
MODEL_PATH = cfg.get("artifacts", {}).get("model", "artifacts/model.joblib")
EXPECTED_COLS = cfg.get("data", {}).get("input_columns", None)
if EXPECTED_COLS is None:
    # is not present EXPECTED_COLS becomes empty
    EXPECTED_COLS = []

# Create list of columns that will be in the UI, these are the most easily known by a user of our app
ENTRY_COLS = [
    "Company",
    "Altitude",
    "Region",
    "Producer",
    "Harvest.Year",
    "Variety",
    "Expiration"
]

# Narrowing EXPECTED_COLS to just those found in ENTRY_COLS
UI_COLS = [col for col in EXPECTED_COLS if col in ENTRY_COLS]
# The above snippet was generated by chatGPT 5.1 at 1:40p on 11/22/25.


# All column entries for interface, made all empty at first for user to enter values into
empty_df = pd.DataFrame([{col: "" for col in UI_COLS}])
# The above snippet was generated by chatGPT 5.1 at 2:33p on 11/21/25 and modified to traverse the correct list.

"""
Begin cited block
Reference:
    OpenAI. (2025). ChatGPT (Version 5.1) [Large language model]. https://chat.openai.com  
    Conversation on November 22, 2025, used to generate the Gradio UI integration,
    FastAPI request logic, and column-alignment mechanics for the Coffee Cup Points Estimator.
"""
def cup_points_estimator(known_values_list):

    # Convert known_vales_list to Python dict for the API to handle
    if isinstance(known_values_list, pd.DataFrame):
        df = known_values_list.copy()
    else:
        # Convert list-of-lists to DataFrame using UI_COLS
        df = pd.DataFrame(known_values_list, columns=UI_COLS)

        # Build filled rows so all EXPECTED_COLS are present
    filled_rows = []
    for _, row in df.iterrows():
        full_row = {col: None for col in EXPECTED_COLS}
        for key, val in row.items():
            if key in full_row:
                full_row[key] = val if val != "" else None
        filled_rows.append(full_row)

    payload = {"rows": filled_rows}

    try:
        # Making API call using API_KEY defined above and json payload
        response = requests.post(API_URL, json=payload)
        response.raise_for_status()

        # preds are dictionary returned by API
        preds = response.json().get("predictions", [None])
        return preds[0]
    
    # Throw error if server cannot be reached
    except Exception as e:
        return f"Error contacting server: {e}"

# -------------------------End cited block-------------------------------

# Gradio interface that takes interie into table and outputs integer using cup_points_estimator
demo = gr.Interface(    
    fn=cup_points_estimator,

    # Citation: OpenAI. (2025). ChatGPT (Version 5.1) [Large language model]. https://chat.openai.com 
    #   Conversation with ChatGPT on February 11, 2025, used to generate the Gradio app code for a coffee cup-points estimator.
    # This snippet was susequently modified to have the correct headers
    inputs=gr.Dataframe(
        headers=UI_COLS,
        value=empty_df,
        row_count=1,
        col_count=len(UI_COLS),
        interactive=True,
        label="Enter Known Values"
    ),
    outputs=gr.Number(label="Estimated Coffee Cup Points (A score above 80 is generally considered as a speciality coffee)"),
    # ----------------END CITED BLOCK-------------------------

    title="Coffee Cup Points Estimator",
    description="Enter known values for coffee into table. The estimated Cop Score from a Q Grader trained by the Coffee Quality Institute will be predicted."
)

# Launch for local testing
demo.launch()
